services:

  postgres:
    image: ankane/pgvector
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z


volumes:
  local_postgres_data: {}
