services:

  unstructured:
    image: quay.io/unstructured-io/unstructured-api:latest
    ports:
      - 8000:8000
    restart: always

  postgres:
    image: ankane/pgvector
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z


volumes:
  local_postgres_data: {}
