# Generated by Django 5.1.3 on 2024-11-30 18:49

import core.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", core.models.CoreUserManager()),
            ],
        ),
    ]
