# Generated by Django 5.1.3 on 2024-12-03 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Citation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_in_answer",
                    models.TextField(
                        help_text="Exact part of text from `answer` that references a source, include formatting."
                    ),
                ),
                (
                    "text_in_source",
                    models.TextField(
                        help_text="Exact part of text from `source` that supports the `answer`"
                    ),
                ),
                (
                    "reference",
                    models.TextField(
                        help_text="reference to the source, could be a file-name, url or uri"
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                (
                    "chat_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.chatmessage",
                    ),
                ),
            ],
        ),
    ]
