# Generated by Django 5.1.4 on 2024-12-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_citation"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="processing_error",
            field=models.TextField(
                blank=True, help_text="error encountered during processing", null=True
            ),
        ),
    ]
