apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: rg.fr-par.scw.cloud/account-registry/dosac-web:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: scw-registry-secret