apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: rg.fr-par.scw.cloud/account-registry/dosac-web:latest
          ports:
            - containerPort: 8080
          env:
            - name: LLM_MODEL
              value: "gpt-4o-mini"
            - name: LLM_MODEL_PROVIDER
              value: "openai"
            - name: EMBEDDING_MODEL
              value: "text-embedding-3-large"
            - name: OPENAI_API_VERSION
              value: "2024-02-01"
            - name: AWS_STORAGE_BUCKET_NAME
              value: "dosac-bucket2"
            - name: AWS_S3_ENDPOINT_URL
              value: "https://dosac-bucket2.s3.fr-par.scw.cloud"
            - name: APP_HOST
              value: "51.159.11.144"
            - name: DEBUG
              value: "True"
          envFrom:
            - secretRef:
                name: secret
      imagePullSecrets:
        - name: scw-registry-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: rg.fr-par.scw.cloud/account-registry/dosac-web:latest
          command: ["poetry", "run", "python", "manage.py", "qcluster"]
          env:
            - name: LLM_MODEL
              value: "gpt-4o-mini"
            - name: LLM_MODEL_PROVIDER
              value: "openai"
            - name: EMBEDDING_MODEL
              value: "text-embedding-3-large"
            - name: OPENAI_API_VERSION
              value: "2024-02-01"
            - name: AWS_STORAGE_BUCKET_NAME
              value: "dosac-bucket2"
            - name: AWS_S3_ENDPOINT_URL
              value: "https://dosac-bucket2.s3.fr-par.scw.cloud"
            - name: APP_HOST
              value: "51.159.11.144"
            - name: DEBUG
              value: "True"
          envFrom:
            - secretRef:
                name: secret
      imagePullSecrets:
        - name: scw-registry-secret