name: Build & Deploy to Scaleway

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        echo rg.fr-par.scw.cloud/account-registry/dosac-web:latest
        docker build . -t rg.fr-par.scw.cloud/account-registry/dosac-web:latest
    - name: Login to Scaleway Container Registry
      uses: docker/login-action@v3
      with:
        username: nologin
        password: ${{ secrets.SCALEWAY_API_KEY }}
        registry: rg.fr-par.scw.cloud/account-registry
    - name: Push the Docker Image
      run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/dosac-web:latest
