name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Scaleway Container Registry
        run: echo "${{ secrets.SCW_PASSWORD }}" | docker login rg.fr-par.scw.cloud/mynamespace -u nologin --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: rg.fr-par.scw.cloud/account-registry/dosac-web:latest
          platforms: linux/amd64  # Typically used; adjust as needed