name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
<<<<<<< Updated upstream
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Scaleway Container Registry
        run: echo "${{ secrets.SCW_PASSWORD }}" | docker login rg.fr-par.scw.cloud/mynamespace -u nologin --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: rg.fr-par.scw.cloud/account-registry/dosac-web:latest
          platforms: linux/amd64  # Typically used; adjust as needed
=======
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/dosac-web:latest
    - name: Login to Scaleway Container Registry
      uses: docker/login-action@v3
      with:
        username: nologin
        password: ${{ secrets.SCALEWAY_API_KEY }}
        registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
    - name: Push the Docker Image
      run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/dosac-web:latest
>>>>>>> Stashed changes
