name: Python application

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
  workflow_dispatch:


jobs:
  checks:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Build Containers
      run: |
        cp .env.example .env
        sed -i -e "s/^POSTGRES_HOST=.*/POSTGRES_HOST=localhost/" .env
        sed -i -e "s/^MINIO_HOST=.*/MINIO_HOST=localhost/" .env
        docker compose up -d --wait postgres minio

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Set up Poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: 1.7.0

    - name: Install dependencies
      run: |
        poetry install

    - name: Check Formatting
      run: make format

    - name: Run Tests
      run: make test

